export { HomePage } from "./HomePage";
export { LoginPage } from "./LoginPage";
export { RegistrationPage } from "./RegistrationPage";
export { NotFoundPage } from "./NotFoundPage";
export { QuestionsPage } from "./QuestionsPage";
export { CollectionsPage } from "./CollectionsPage";
export { StatisticsPage } from "./StatisticsPage";
export { CreateCollectionPage } from "./CreateCollectionPage";
export { EditCollectionPage } from "./EditCollectionPage";
